version: '3'

services:
  log-service-1:
    build:
      context: ./server/log_service
      dockerfile: Dockerfile
    environment:
      - PORT=3000
  log-service-2:
    build:
      context: ./server/log_service
      dockerfile: Dockerfile
    environment:
      - PORT=3000
  nginx:
    image: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - log-service-1
      - log-service-2
