version: '3'

services:
  zookeeper:
    image: 'wurstmeister/zookeeper:latest'
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - kafka-net

  kafka-1:
    image: 'wurstmeister/kafka:latest'
    container_name: kafka-1
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - kafka-net
  
  kafka-2:
    image: 'wurstmeister/kafka:latest'
    container_name: kafka-2
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-2:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - kafka-net

  log-producer-1:
    container_name: log-producer-1
    build:
      context: ./server/log_producer
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - KAFKA_ADDR=kafka-1:9092,kafka-2:9092
    depends_on:
      - kafka-1
      - kafka-2
    networks:
      - kafka-net

  log-producer-2:
    container_name: log-producer-2
    build:
      context: ./server/log_producer
      dockerfile: Dockerfile
    environment:
      - PORT=3000
      - KAFKA_ADDR=kafka-1:9092,kafka-2:9092
    depends_on:
      - kafka-1
      - kafka-2
    networks:
      - kafka-net


  log-producer-nginx:
    image: nginx
    container_name: log-producer-nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx/log-producer.conf:/etc/nginx/nginx.conf
    depends_on:
      - log-producer-1
      - log-producer-2
    networks:
      - kafka-net

  log-consumer:
    container_name: log-consumer
    build:
      context: ./server/log_consumer
      dockerfile: Dockerfile
    environment:
      - KAFKA_ADDR=kafka-1:9092,kafka-2:9092
    depends_on:
      - kafka-1
      - kafka-2
    networks:
      - kafka-net

networks:
  kafka-net:
    driver: bridge

